# AMOSKYS Service Accounts
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: amoskys-web
  labels:
    app.kubernetes.io/name: amoskys
    app.kubernetes.io/component: web
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: amoskys-agent
  labels:
    app.kubernetes.io/name: amoskys
    app.kubernetes.io/component: agent
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus
  labels:
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/component: monitoring
